language: python
sudo: required
python:
  - '3.6'
install:
  - pip install --no-binary numpy --upgrade numpy
  - pip install -r requirements.txt
script:
  - >-
    export
    PYTHONPATH=./facenet_sandberg:./facenet_sandberg/models:./facenet_sandberg/align
  - python -m unittest discover -s test --pattern=*.py 1>&2
dist: trusty
