# Automatically generated by Pynguin.
import download_and_extract as module_0


def test_case_0():
    try:
        bool_0 = False
        var_0 = module_0.get_confirm_token(bool_0)
    except BaseException:
        pass
